repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--config", "pyproject.toml", "build", "tests"]
      - id: ruff-format
        args: ["--config", "pyproject.toml", "build", "tests"]